# Generated by Django 2.0.3 on 2019-03-14 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(limit_value=0.01, message='O valor deve ser, pelo menos, R$0,01.')]),
        ),
    ]
