# Generated by Django 2.0.3 on 2019-03-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0002_auto_20190314_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
